# Use staging's Thingpedia
WITH_THINGPEDIA: external
THINGPEDIA_URL: https://dev.almond.stanford.edu/thingpedia

# Use staging's LUInet
WITH_LUINET: external

ENABLE_DEVELOPER_PROGRAM: false
ENABLE_ANONYMOUS_USER: true

# Point to the local instance
SERVER_ORIGIN: http://127.0.0.1:8080 # TODO or :7070 ?
OAUTH_REDIRECT_ORIGIN: http://127.0.0.1:8080 # TODO or :7070 ?

ENABLE_REDIRECT: true

# No HTTPS on local dev instances
ENABLE_SECURITY_HEADERS: false

USE_BRAND: stanford

SUPPORTED_LANGUAGES:
  - en-US

# Copied from `@/src/config.ts`
FILE_STORAGE_DIR: ./shared/download
CDN_HOST: /download

THINGENGINE_MANAGER_ADDRESS:
  - backend.almond-dev.svc.cluster.local:8100

DATABASE_PROXY_URL: http://dbproxy.almond-dev.svc.cluster.local:8200

# Use staging's NL server
NL_SERVER_URL: https://nlp-staging.almond.stanford.edu

# From `@/src/config.js`
NL_MODEL_DIR: ./models
NL_EXACT_MATCH_DIR: ./exact

MS_SPEECH_SERVICE_REGION: westus2

# From `@/src/config.js`
TRAINING_DIR: ./training
TRAINING_URL: null

# From `@/src/config.js`
TENSORBOARD_DIR: null
TRAINING_MEMORY_USAGE: 24000

# From `@/src/config.js`
TRAINING_TASK_BACKEND: kubernetes

TRAINING_KUBERNETES_IMAGE: stanfordoval/almond-cloud:v2.0.0-126-gae1bee9

# Dev namespace
TRAINING_KUBERNETES_NAMESPACE: almond-dev

TRAINING_KUBERNETES_POD_SPEC_OVERRIDE:
  serviceAccountName: training-pod
  securityContext:
    fsGroup: 65534
  volumes:
    - name: config
      configMap:
        name: almond-config-h8dd66g7gt
    - name: secret
      secret:
        secretName: almond-secret-5bhc6b9hb5

TRAINING_KUBERNETES_CONTAINER_SPEC_OVERRIDE:
  volumeMounts:
    - mountPath: /etc/almond-cloud/config.d/config.yaml
      subPath: config.yaml
      name: config
      readOnly: true
    - mountPath: /etc/almond-cloud/config.d/secret.yaml
      subPath: secret.yaml
      name: secret
      readOnly: true


EMAIL_FROM_USER: '[DEV] Almond <noreply@almond-dev.stanford.edu>'
EMAIL_FROM_ADMIN: '[DEV] Almond <root@almond-dev.stanford.edu>'
EMAIL_FROM_TRAINING: '[DEV] Almond Training Service <almond-dev-training@almond-dev.stanford.edu>'
EMAIL_TO_ADMIN: 'thingpedia-admins@lists.stanford.edu'
MAILGUN_USER: postmaster@almond.stanford.edu

# From `@/src/config.js`
ENABLE_PROMETHEUS: true
USE_KF_INFERENCE_SERVICE: true

# these features are disabled on staging and dev instances
GOOGLE_CLIENT_ID: null
GITHUB_CLIENT_ID: null
MAPQUEST_KEY: null

# From `@/src/config.js`
DISCOURSE_SSO_REDIRECT: null

ABOUT_OVERRIDE:
  index: 'stanford/about_index.pug'
  tos: 'stanford/about_tos.pug'
  privacy: 'stanford/about_privacy.pug'

EXTRA_ABOUT_PAGES:
  - url: 'get-almond'
    view: 'stanford/about_get_almond.pug'
    title: 'Get Almond'
  - url: 'get-involved'
    view: 'stanford/about_get_involved.pug'
    title: 'Get Involved With Almond'

EXTRA_NAVBAR:
  - url: 'https://oval.cs.stanford.edu'
    title: 'OVAL Lab'

REGISTRATION_WARNING: >
  This is the <strong>development</strong> version of Genie. It is not suitable
  for everyday use. You should not use this server to store any sensitive or
  important data.
  <strong>Your account and your data might be deleted at any time without warning!</strong>
