apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# TODO Needed? Does the same in ../kustomization.yaml not take care of it?
# namespace: almond-dev

resources:
  - namespace.yaml
  - sa.yaml

configMapGenerator:
- name: almond-config
  files:
    - config.yaml
- name: manager-config
  files:
    - manager-config/developer-deployment.json
    - manager-config/developer-service.json

secretGenerator:
- name: almond-secret
  files:
    - secret.yaml
