apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# TODO Needed? Does the same in ../kustomization.yaml not take care of it?
# namespace: almond-dev

resources:
  - namespace.yaml

configMapGenerator:
- name: almond-config
  files:
    - config.yaml

secretGenerator:
- name: almond-secret
  files:
    - secret.yaml

secretGenerator:
- name: almond-secret-kv
  envs:
    - .env.secret
