---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: development
