# Almond Cloud Configuration
# ============================================================================

# MySQL (MariaDB)
# ----------------------------------------------------------------------------

DATABASE_URL: >-
  mysql://root:password@mariadb.almond-dev.svc.cluster.local/thingengine_dev?charset=utf8mb4_bin
DATABASE_PROXY_URL: http://dbproxy.almond-dev.svc.cluster.local:8200

# HTTP
# ----------------------------------------------------------------------------

SERVER_ORIGIN: http://almond.local
ENABLE_REDIRECT: false

# CDN
# ----------------------------------------------------------------------------

CDN_HOST: /download

# Natural Language Server
# ----------------------------------------------------------------------------

WITH_LUINET: embedded

NL_SERVER_URL: https://nlp-staging.almond.stanford.edu

# Thingpedia
# ----------------------------------------------------------------------------

# Use a local thingpedia  
WITH_THINGPEDIA: embedded
THINGPEDIA_URL: /thingpedia

# Use staging's Thingpedia
# WITH_THINGPEDIA: external
# THINGPEDIA_URL: https://dev.almond.stanford.edu/thingpedia

ENABLE_DEVELOPER_PROGRAM: true

ENABLE_DEVELOPER_BACKEND: true

# Prometheus
# ----------------------------------------------------------------------------

ENABLE_PROMETHEUS: true

PROMETHEUS_ACCESS_TOKEN: my-prometheus-access-token
  
# User Experience
# ----------------------------------------------------------------------------

ENABLE_ANONYMOUS_USER: true

USE_BRAND: stanford

ABOUT_OVERRIDE:
  index: stanford/about_index.pug
  tos: stanford/about_tos.pug
  privacy: stanford/about_privacy.pug
  
EXTRA_ABOUT_PAGES:
  - url: get-almond
    view: stanford/about_get_almond.pug
    title: "Get Almond"
  - url: get-involved
    view: stanford/about_get_involved.pug
    title: "Get Involved With Almond"

EXTRA_NAVBAR:
  - url: https://oval.cs.stanford.edu
    title: "OVAL Lab"
    
# Single Sign-On (SSO)
# ----------------------------------------------------------------------------

### Discourse ###

DISCOURSE_SSO_SECRET: d836444a9e4084d5b224a60c208dce14

DISCOURSE_SSO_REDIRECT: https://discourse.almond.stanford.edu

# Security
# ----------------------------------------------------------------------------

AES_SECRET_KEY: 80bb23f93126074ba01410c8a2278c0c

JWT_SIGNING_KEY: "not so secret key"

SECRET_KEY: "not so secret key"

# Languages
# ----------------------------------------------------------------------------

SUPPORTED_LANGUAGES:
  - en-US
  - it-IT
  - zh-CN
  - zh-TW
