apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

bases:
  - ../base

resources:
  - namespace.yaml

patches:
  - namespace.yaml

configMapGenerator:
  - name: almond-config
    files:
      - config.yaml

secretGenerator:
  - name: almond-secret
    files:
      # NOTE  This file must be created locally, see adjacent
      #       `secret.yaml.EXAMPLE` file
      - secret.yaml
