apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

bases:
  - ../base

resources:
  - namespace.yaml

patches:
  - namespace.yaml

configMapGenerator:
  - name: almond-config
    files:
      - config.yaml
  
  # - name: manager-config
  #   files:
  #     - manager-config/developer-deployment.json
  #     - manager-config/developer-service.json

secretGenerator:
  - name: almond-secret
    files:
      - secret.yaml
