---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -c
            - |
              set -ex
              cd /opt/almond-cloud
              /usr/bin/npm run debug
          volumeMounts:
            - mountPath: /opt/almond-cloud/src
              name: src
            - mountPath: /opt/almond-cloud/views
              name: views
            - mountPath: /home/almond-cloud/shared
              name: shared
      volumes:
        - name: src
          hostPath:
            # directory location on host
            path: /Users/nrser/src/github.com/stanford-oval/almond-cloud/src
            # this field is optional
            type: Directory
        - name: views
          hostPath:
            path: /Users/nrser/src/github.com/stanford-oval/almond-cloud/views
            type: Directory
        - name: shared
          hostPath:
            # directory location on host
            path: /Users/nrser/src/github.com/stanford-oval/almond-cloud/tmp/shared
            # this field is optional
            type: DirectoryOrCreate
