apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../base

patches:
  - deployment.yaml
  # NOTE  This file must be created locally, see adjacent
  #       `deployment.local.yaml.EXAMPLE` file
  - deployment.local.yaml