apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: almond-dev
components:
  - ../../../components/config/dev
  - ../../../components/db/dev
  - ../../../components/redis/dev
  - ../../../components/frontend/dev
  - ../../../components/dbproxy/dev
  - ../../../components/shared-backend/dev
  - ../../../components/controller/crd/dev
  - ../../../components/controller/rbac/dev
  - ../../../components/controller/manager/dev

images:
  - name: stanfordoval/almond-cloud
    newName: localhost/almond-cloud

transformers:
  - ../../../plugins/resolve-host-paths/transformer.yaml
