apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: almond-dev
components:
  - ../../../components/config/dev
  - ../../../components/nlp/debug

images:
  - name: stanfordoval/almond-cloud
    newName: localhost/almond-cloud

transformers:
  - ../../../plugins/resolve-host-paths/transformer.yaml
