apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "shared-backend"
spec:
  selector:
    matchLabels:
      app: "shared-backend"
  replicas: 1
  serviceName: shared-backend
  template:
    metadata:
      labels:
        app: "shared-backend"
    spec:
      serviceAccountName: default-editor
      containers:
      - name: "main"
        image: stanfordoval/almond-cloud:latest
        imagePullPolicy: IfNotPresent
        args:
        - run-worker
        - --thingpedia-url=https://dev.almond.stanford.edu/thingpedia
        - --nl-server-url=https://nlp-staging.almond.stanford.edu
        - --oauth-redirect-origin=https://dev.almond.stanford.edu
        - --faq-models={}
        - --notification-config={}
        - --locale=en-US
        workingDir: /srv/thingengine
        volumeMounts:
        - mountPath: /srv/thingengine
          name: local-storage
        resources:
          requests:
            memory: 200M
        ports:
          - containerPort: 8100
            name: almond
      securityContext:
        fsGroup: 65534
      volumes:
      - name: local-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shared-backend
  labels:
    app: shared-backend
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    app: shared-backend
