apiVersion: v1
kind: PersistentVolume
metadata:
  name: src
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/nrser/src/github.com/stanford-oval/almond-cloud/src"
